
[build]
  publish = "dist"
  command = "npm run build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "https://taxfreechildcarecalculator.netlify.app/*"
  to = "https://taxfreechildcarecalculator.net/:splat"
  status = 301
  force = true
